import { categories } from "./categories";
import { priority } from "./priority";
import { statuses } from "./statuses";

export const mockTickets = [
  {
    id: 1,
    number: "КС-0002",
    pharmacyCode: "065",
    pharmacyName: "Геленджик Островского 7",
    createdAt: "20.07.2025 12:35:45",
    priority: priority.high,
    topic: "Поломка кассы",
    category: categories.cashRegisters,
    technician: "—",
    reaction: " 02:48",
    resolution: "—",
    status: statuses.new,
  },
  {
    id: 2,
    number: "ХЛ-0002",
    pharmacyCode: "150",
    pharmacyName: "Кореновск Красная 108",
    createdAt: "20.07.2025 12:35:45",
    priority: priority.mid,
    topic: "Холодильник сильно гудит",
    category: categories.refrigerators,
    technician: "Федоровский Н.",
    reaction: " 05:01",
    resolution: " 01:35:34",
    status: statuses.processed,
  },
  {
    id: 3,
    number: "КН-0002",
    pharmacyCode: "045",
    pharmacyName: "Тимашевск Интернац 3Б",
    createdAt: "20.07.2025 12:35:45",
    priority: priority.low,
    topic: "Конденсат на внутреннем блоке",
    category: categories.conditioners,
    technician: "Максимов П.",
    reaction: " 05:01",
    resolution: " 02:30:17",
    status: statuses.ready,
  },
  {
    id: 4,
    number: "ИЗ-0002",
    pharmacyCode: "164",
    pharmacyName: "РНД Сельмаш 92",
    createdAt: "20.07.2025 12:35:45",
    priority: priority.critical,
    topic: "Нужно поверить гигрометр",
    category: categories.measuringEquipment,
    technician: "Алексеев М.",
    reaction: " 05:01",
    resolution: " 02:30:17",
    status: statuses.ready,
  },
  {
    id: 5,
    number: "ПО-0002",
    pharmacyCode: "190",
    pharmacyName: "Геленджик Душистая 24",
    createdAt: "20.07.2025 12:35:45",
    priority: priority.high,
    topic: "Заметили крыс у входа",
    category: categories.premises,
    technician: "Сидоров Е.",
    reaction: " 05:01",
    resolution: " 02:30:17",
    status: statuses.closed,
  },
  {
    id: 6,
    number: "ИТ-0002",
    pharmacyCode: "267",
    pharmacyName: "Анапа Парковая 67к2",
    createdAt: "20.07.2025 12:35:45",
    priority: priority.high,
    topic: "Нужен новый компьютер",
    category: categories.it,
    technician: "Китов Я.",
    reaction: " 05:01",
    resolution: " 02:30:17",
    status: statuses.closed,
  },
  {
    id: 7,
    number: "СА-0002",
    pharmacyCode: "150",
    pharmacyName: "Кореновск Красная 108",
    createdAt: "20.07.2025 12:35:45",
    priority: priority.mid,
    topic: "Унитаз перестал смывать",
    category: categories.plumbing,
    technician: "Малахов Н.",
    reaction: " 05:01",
    resolution: " 02:30:17",
    status: statuses.ready,
  },
];
